[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line hex viewer"
homepage = "https://github.com/sharkdp/hexyl"
license = "MIT/Apache-2.0"
name = "hexyl"
readme = "README.md"
repository = "https://github.com/sharkdp/hexyl"
version = "0.11.0"
edition = "2021"

[dependencies]
anstyle = "0.2"
anyhow = "1.0"
const_format = "0.2"
is-terminal = "0.4"
rustix = "0.36"
thiserror = "1.0"
terminal_size = "0.2"

[dependencies.clap]
version = "4"
default-features = false
features = ["std", "suggestions", "color", "wrap_help", "cargo", "help", "usage", "error-context"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.0"
pretty_assertions = "1.3.0"

[profile.release]
lto = true
codegen-units = 1
